version: '2'

services:
    web:
        build: ./web
        depends_on:
            - 'rabbitmq'
            - 'postgres'
    interface:
        build: ./interface
        depends_on:
            - 'rabbitmq'
            - 'postgres'
        devices:
            - '/dev/ttyACM0:/dev/tty.app'
    rabbitmq:
        image: 'cyrilix/rabbitmq-mqtt:latest'
    postgres:
        image: 'library/postgres:9.6.1-alpine'
