version: '2'

services:
    web:
        build: ./web
        depends_on:
            - 'rabbitmq'
            - 'postgres'
        environment:
            - 'PGUSER=postgres'
            - 'PGHOST=postgres'
            - 'PGDATABASE=postgres'
        ports:
            - '80:8080'
    interface:
        build: ./interface
        depends_on:
            - 'rabbitmq'
            - 'postgres'
        devices:
            - '/dev/ttyACM0:/dev/tty.app'
        environment:
            - 'COM=/dev/tty.app'
            - 'MQTT=rabbitmq:1883'
            - 'PSQL=postgres://postgres@postgres:5432?sslmode=disable'
    rabbitmq:
        image: 'cyrilix/rabbitmq-mqtt:latest'
    postgres:
        image: 'postgres:9.6.1-alpine'
